language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t herederpharao/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true herederpharao/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-eu-central-1-727700104260"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"